{
	"aircraft_type" : {
		"100" : "Fokker 100",
		"141" : "BAe 146-100",
		"142" : "BAe 146-200",
		"143" : "BAe 146-300",
		"146" : "BAe 146",
		"310" : "Airbus A310",
		"312" : "Airbus A310-200",
		"313" : "Airbus A310-300",
		"318" : "Airbus A318",
		"319" : "Airbus A319",
		"320" : "Airbus A320",
		"321" : "Airbus A321",
		"322" : "Airbus A320-200",
		"330" : "Airbus A330",
		"332" : "Airbus A330-200",
		"333" : "Airbus A330-300",
		"340" : "Airbus A340",
		"342" : "Airbus A340-200",
		"343" : "Airbus A340-300",
		"345" : "Airbus A340-500",
		"346" : "Airbus A340-600",
		"350" : "Airbus A350",
		"351" : "Airbus A350-1000",
		"358" : "Airbus A350-800",
		"359" : "Airbus A350-900",
		"380" : "Airbus A380",
		"388" : "Airbus A380-800",
		"703" : "Boeing 707",
		"707" : "Boeing 707",
		"717" : "Boeing 717-200",
		"721" : "Boeing 727-100",
		"722" : "Boeing 727-200",
		"727" : "Boeing 727",
		"731" : "Boeing 737-100",
		"732" : "Boeing 737-200",
		"733" : "Boeing 737-300",
		"734" : "Boeing 737-400",
		"735" : "Boeing 737-500",
		"736" : "Boeing 737-600",
		"737" : "Boeing 737",
		"738" : "Boeing 737-800",
		"739" : "Boeing 737-900",
		"741" : "Boeing 747-100",
		"742" : "Boeing 747-200",
		"743" : "Boeing 747-300",
		"744" : "Boeing 747-400",
		"747" : "Boeing 747",
		"752" : "Boeing 757-200",
		"753" : "Boeing 757-300",
		"757" : "Boeing 757",
		"762" : "Boeing 767-200",
		"763" : "Boeing 767-300",
		"764" : "Boeing 767-400",
		"765" : "Boeing 767-500",
		"767" : "Boeing 767",
		"772" : "Boeing 777-200",
		"773" : "Boeing 777-300",
		"777" : "Boeing 777",
		"783" : "Boeing 787-3",
		"787" : "Boeing 787",
		"788" : "Boeing 787-8",
		"789" : "Boeing 787-9",
		"14F" : "BAe 146 Freighter",
		"21F" : "Airbus A321",
		"31F" : "Airbus A310 Freighter",
		"31X" : "Airbus A310-200 Freighter",
		"31Y" : "Airbus A310-300 Freighter",
		"32A" : "Airbus A320",
		"32B" : "Airbus A321",
		"32F" : "Airbus A320 Freighter",
		"32N" : "Airbus A320",
		"32S" : "Airbus A320",
		"32X" : "Airbus A321 Freighter",
		"32Z" : "Airbus A320-200",
		"38F" : "Airbus A380 Freighter",
		"70F" : "Boeing 707 Freighter",
		"70M" : "Boeing 707",
		"72A" : "Boeing 727-200",
		"72B" : "Boeing 727-100",
		"72C" : "Boeing 727-200",
		"72F" : "Boeing 727 Freighter",
		"72M" : "Boeing 727-100",
		"72S" : "Boeing 727-200",
		"72W" : "Boeing 727-200",
		"72X" : "Boeing 727-100 Freighter",
		"72Y" : "Boeing 747-200 Freighter",
		"73A" : "Boeing 737-200",
		"73C" : "Boeing 737-300",
		"73E" : "Boeing 737-500",
		"73F" : "Boeing 737-700 Freighter",
		"73G" : "Boeing 737-700",
		"73H" : "Boeing 737-800",
		"73I" : "Boeing 737",
		"73J" : "Boeing 737-900",
		"73L" : "Boeing 737-200",
		"73M" : "Boeing 737-200",
		"73N" : "Boeing 737-300",
		"73P" : "Boeing 737-400 Freighter",
		"73Q" : "Boeing 737-400",
		"73R" : "Boeing 737-700",
		"73S" : "Boeing 737-700 Freighter",
		"73V" : "Boeing 737",
		"73W" : "Boeing 737-700",
		"73X" : "Boeing 737-200 Freighter",
		"74B" : "Boeing 747-400 Freighter",
		"74C" : "Boeing 747-200",
		"74D" : "Boeing 747-300",
		"74E" : "Boeing 747-400",
		"74F" : "Boeing 747 Freighter",
		"74H" : "Boeing 747-8I",
		"74J" : "Boeing 747-400",
		"74L" : "Boeing 747SP",
		"74M" : "Boeing 747",
		"74N" : "Boeing 747-8F Freighter",
		"74R" : "Boeing 747SR",
		"74T" : "Boeing 747-100 Freighter",
		"74V" : "Boeing 747-300 Freighter",
		"74X" : "Boeing 747 Freighter",
		"74Y" : "Boeing 747-400 Freighter",
		"75F" : "Boeing 757 Freighter",
		"75M" : "Boeing 757-200",
		"75O" : "Boeing 757-200",
		"75S" : "Boeing 757",
		"75T" : "Boeing 757-300",
		"75W" : "Boeing 757-200",
		"76F" : "Boeing 767 Freighter",
		"76G" : "Boeing 767-300ER",
		"76P" : "Boeing 767",
		"76V" : "Boeing 747-300 Freighter",
		"76W" : "Boeing 767-300",
		"76X" : "Boeing 767-200 Freighter",
		"76Y" : "Boeing 747-300 Freighter",
		"76Z" : "Boeing 767-300",
		"77F" : "Boeing 777 Freighter",
		"77L" : "Boeing 777-200LR",
		"77W" : "Boeing 777-300ER",
		"77X" : "Boeing 777-200 Freighter",
		"A22" : "Antonov AN-22",
		"A26" : "Antonov AN-26",
		"A28" : "Antonov AN-28",
		"A30" : "Antonov AN-30",
		"A32" : "Antonov AN-32",
		"A38" : "Antonov AN-38",
		"A40" : "Antonov AN-140",
		"A4F" : "Antonov AN-124 Freighter",
		"A58" : "Antonov AN-158",
		"A5F" : "Jetprop Commander",
		"A81" : "Antonov AN-148-100",
		"AB3" : "Airbus A300",
		"AB4" : "Airbus A300-B2/B4/C4",
		"AB6" : "Airbus A300-600/600C",
		"ABB" : "Airbus A300-600ST Beluga",
		"ABF" : "Airbus A300 Freighter",
		"ABM" : "Airbus A300-C4 Mixed",
		"ABX" : "Airbus A300 Freighter",
		"ABY" : "Airbus A300-600 Freighter",
		"ACD" : "Rockwell Aero Commander",
		"ACP" : "Aerospace Commander",
		"ACT" : "Aerospace Commander",
		"AGH" : "Agusta A109A",
		"AN2" : "Antonov AN-2",
		"AN4" : "Antonov AN-24",
		"AN6" : "Antonov AN-26",
		"AN7" : "Antonov AN-72/74",
		"ANF" : "Antonov AN-12 Freighter",
		"APH" : "Eurocopter",
		"AR1" : "Avro RJ100 Avroliner",
		"AR7" : "Avro RJ70 Avroliner",
		"AR8" : "Avro RJ85 Avroliner",
		"ARJ" : "Avro RJ Avroliner",
		"ARX" : "Avro RJX Avroliner",
		"AT3" : "Alenia ATR 42",
		"AT4" : "Alenia ATR 42-300/320",
		"AT5" : "Alenia ATR 42-500",
		"AT7" : "Alenia ATR 72",
		"ATD" : "Alenia ATR 42-400",
		"ATF" : "ATR 42 Freighter",
		"ATP" : "British Aerospace ATP",
		"ATR" : "Alenia ATR 42/72",
		"ATX" : "Alenia ATR 72",
		"AWH" : "Agusta Westland",
		"AX1" : "Avro RJX100 Avroliner",
		"AX8" : "Avro RJX85 Avroliner",
		"B10" : "Beechcraft 200",
		"B11" : "BAC 1-11",
		"B12" : "BAC 1-11 300",
		"B13" : "BAC 1-11 400",
		"B14" : "BAC 1-11 500",
		"B72" : "Boeing 720",
		"B75" : "Boeing 757",
		"BE1" : "Beechcraft 1900",
		"BE2" : "Beechcraft",
		"BE4" : "Hawker 400 Beechjet",
		"BE9" : "Beechcraft C99 Airliner",
		"BEB" : "Beechcraft Baron",
		"BEC" : "Beechcraft Light Aircraft",
		"BEF" : "Hawker Beechcraft 1900 Freighter",
		"BEH" : "Beechcraft 1900D",
		"BEO" : "Beechcraft Twin Bonanza",
		"BEP" : "Hawker Beechcraft Light Aircraft",
		"BEQ" : "Beechcraft Queen Air",
		"BES" : "Beechcraft 1900",
		"BET" : "Beechcraft",
		"BNI" : "Norman Islander",
		"BNT" : "Norman Trislander",
		"C21" : "Comac ARJ21",
		"C27" : "Comac ARJ21-700",
		"CCJ" : "Canadair Challenger",
		"CD2" : "N24A Nomad",
		"CJ1" : "Cessna 500",
		"CJ2" : "Cessna Citation",
		"CJ5" : "Cessna 560 Citation",
		"CJ6" : "Cessna 650 Citation",
		"CJ7" : "Cessna 680 Citation",
		"CJL" : "Cessna 560 Citation",
		"CJM" : "Cessna 510",
		"CN1" : "Cessna 40",
		"CN2" : "Cessna Stationair 206",
		"CN4" : "Cessna 402",
		"CN7" : "Cessna 750 Citation X",
		"CNA" : "Cessna (Light Aircraft)",
		"CNC" : "Cessna",
		"CND" : "Cessna Titan",
		"CNF" : "Cessna 208B Freighter",
		"CNJ" : "Cessna Citation",
		"CNT" : "Cessna Twin Turboprop",
		"CR1" : "Canadair Regional Jet 100",
		"CR2" : "Canadair Regional Jet 200",
		"CR7" : "Canadair Regional Jet 700",
		"CR9" : "Canadair Regional Jet 900",
		"CRA" : "Canadair CRJ Series 705",
		"CRB" : "Aerospatiale Caravelle",
		"CRJ" : "Canadair Regional Jet",
		"CRK" : "Canadair Regional Jet 1000",
		"CRS" : "Aerospatiale Super Caravelle",
		"CRV" : "Aerospatiale Caravelle",
		"CS2" : "CASA C-212 Aviocar",
		"CS5" : "CASA CN-235",
		"CV2" : "Convair 240",
		"CV4" : "Convair 440 Metropolitan",
		"CV5" : "Convair 580",
		"CV6" : "Convair 600/640",
		"CVF" : "Convair Freighter",
		"CVR" : "Convair 240-640",
		"CVV" : "Convair 240 Freighter",
		"CVX" : "Convair 340/400 Freighter",
		"CVY" : "Convair 580/640 Freighter",
		"CWC" : "Curtiss C-46 Commando",
		"D10" : "DC10",
		"D11" : "DC10-10/15",
		"D14" : "DC10-40",
		"D1C" : "DC10-30/40",
		"D1F" : "DC10 Freighter",
		"D1M" : "DC10-30",
		"D1X" : "DC10-10 Freighter",
		"D1Y" : "DC10-30 Freighter",
		"D1Z" : "DC10-30",
		"D28" : "Dornier 228",
		"D2L" : "Falcon 2000EX",
		"D38" : "Dornier 328",
		"D3F" : "DC3 Freighter",
		"D3M" : "Douglas DC3",
		"D42" : "Diamond DA42",
		"D6F" : "Douglas DC6 Freighter",
		"D85" : "DC8-50",
		"D86" : "DC8 Super 61",
		"D87" : "DC8 Super 71",
		"D8A" : "DC8 Super 63",
		"D8B" : "DC8 Super 73",
		"D8F" : "DC8 Freighter",
		"D8L" : "DC8 Super 62",
		"D8M" : "Dornier 228",
		"D8Q" : "DC8 Super 72",
		"D8S" : "DC8",
		"D8T" : "DC8 Freighter",
		"D8X" : "DC8 Freighter",
		"D8Y" : "DC8 Freighter",
		"D91" : "DC9-10/15",
		"D92" : "DC9-20",
		"D93" : "DC9-30",
		"D94" : "DC9-40",
		"D95" : "DC9-50",
		"D98" : "DC9-80",
		"D9C" : "DC9 Freighter",
		"D9D" : "DC9 Freighter",
		"D9F" : "DC9 Freighter",
		"D9L" : "Falcon 900LX",
		"D9S" : "DC9-30/40/50",
		"D9X" : "DC9 Freighter",
		"DAM" : "Dassault Mercure",
		"DC3" : "DC3",
		"DC4" : "DC4",
		"DC6" : "DC6A/B",
		"DC8" : "DC8",
		"DC9" : "DC9 Freighter",
		"DF1" : "Falcon 10/100",
		"DF2" : "Mystere-Falcon 10/20",
		"DF3" : "Mystere-Falcon 50/90",
		"DF5" : "Falcon 50/50EX",
		"DF7" : "Falcon 7X",
		"DF9" : "Falcon 900",
		"DFL" : "Mystere-Falcon",
		"DH1" : "Dash 8 100 Series",
		"DH2" : "Dash 8 200 Series",
		"DH3" : "Dash 8 300 Series",
		"DH4" : "Dash 8 400 Series",
		"DH7" : "Dash 7",
		"DH8" : "Dash 8",
		"DHB" : "DHC-2 Turbo Beaver",
		"DHC" : "DHC-4 Caribou",
		"DHF" : "Dash 8 Freighter",
		"DHL" : "DHC-3 Turbo Otter",
		"DHO" : "DHC-3 Otter",
		"DHP" : "DHC-2 Beaver",
		"DHR" : "DHC-2 Turbo Beaver",
		"DHT" : "DHC-6 Twin Otter",
		"DO2" : "Dornier DO228",
		"DO8" : "Dornier DO228",
		"E70" : "Embraer 170",
		"E75" : "Embraer 175",
		"E90" : "Embraer 190",
		"E95" : "Embraer 195",
		"EA5" : "Eclipse 500",
		"EC3" : "Eurocopter EC130",
		"EM2" : "Embraer EMB-120",
		"EM4" : "Embraer EMB-145",
		"EM7" : "Embraer RJ170",
		"EM9" : "Embraer RJ190",
		"EMB" : "Embraer EMB-110",
		"EP1" : "Embraer EMB-500",
		"EP3" : "Embraer EMB-550",
		"ER3" : "Embraer RJ135",
		"ER4" : "Embraer RJ145",
		"ERD" : "Embraer RJ140",
		"F21" : "Fokker F28-1000",
		"F22" : "Fokker F28-2000",
		"F23" : "Fokker F28-3000",
		"F24" : "Fokker F28-4000",
		"F27" : "Fokker F27",
		"F28" : "Fokker F28",
		"F2A" : "Fokker F27-100",
		"F2D" : "Fokker F27-400",
		"F2S" : "Fokker F27-600",
		"F50" : "Fokker 50",
		"F5F" : "Fokker 50 Freighter",
		"F70" : "Fokker 70",
		"F7B" : "Fokker",
		"FK7" : "Fairchild FH-227",
		"FRJ" : "Fairchild 328JET",
		"GA8" : "GippsAero GA8 Airvan",
		"GR1" : "Gulfstream G100/G150",
		"GR2" : "Gilfstream G200",
		"GR3" : "Gulfstream G250",
		"GRA" : "Grumman G-111 Albatros",
		"GRG" : "Grumman G-21 Goose",
		"GRJ" : "G-1159 Gulfstream",
		"GRM" : "Grumman G-73 Mallard",
		"GRS" : "G-159 Gulfstream",
		"H25" : "BAe 125",
		"H7M" : "HS 748",
		"HPH" : "Handley Page Dart Herald",
		"HPJ" : "Handley Page Jetstream",
		"HS7" : "HS748",
		"HSF" : "Hawker Siddeley Argosy",
		"I14" : "Ilyushin IL-114",
		"I9F" : "Ilyushin IL-96 Freighter",
		"IL4" : "Ilyushin IL-14",
		"IL6" : "Ilyushin IL-62/62M/62MK",
		"IL7" : "Ilyushin IL-76 Freighter",
		"IL8" : "Ilyushin IL-18",
		"IL9" : "Ilyushin IL-96",
		"ILW" : "Ilyushin IL-86",
		"J31" : "Jetstream 31",
		"J32" : "Jetstream 32",
		"J41" : "Jetstream 41",
		"JST" : "Jetstream",
		"JU5" : "Junkers JU52",
		"L10" : "Lockheeed Tristar",
		"L11" : "Lockheeed Tristar",
		"L12" : "Lockheeed Tristar",
		"L15" : "Lockheeed Tristar",
		"L19" : "Lockheeed Tristar",
		"L1A" : "Lockheeed Tristar",
		"L1F" : "Lockheeed Tristar",
		"L4T" : "Let L410 Turbolet",
		"LOE" : "Lockheed Electra",
		"LOF" : "Lockheed Electra Freighter",
		"LOH" : "L-100 Hercules",
		"LRJ" : "Learjet",
		"M11" : "MD11",
		"M1F" : "MD11 Freighter",
		"M1M" : "MD11 Freighter",
		"M2F" : "MD82 Freighter",
		"M3F" : "MD83 Freighter",
		"M80" : "MD80",
		"M81" : "MD81",
		"M82" : "MD82",
		"M83" : "MD83",
		"M87" : "MD87",
		"M88" : "MD88",
		"M8F" : "MD88 Freighter",
		"M90" : "MD90",
		"MA6" : "Xian MA60",
		"MBH" : "Eurocopter BO105",
		"MD8" : "MD8",
		"MD9" : "MD900 Explorer",
		"MIH" : "Mil Mi-8",
		"MR4" : "Martin 404",
		"MU2" : "Mitsubishi MU-2",
		"ND2" : "Aerospatiale Mohawk",
		"NDC" : "Aerospatiale Corvette",
		"NDE" : "Aerospatiale Ecureuil",
		"NDH" : "Aerospatiale Dauphin",
		"P12" : "Pilatus",
		"P18" : "Piaggio Aero P180 Avanti",
		"PA1" : "Piper T1020/1040",
		"PA2" : "Piper Light Aircraft",
		"PA6" : "Piper Aerostar",
		"PAC" : "Piper Cherokee",
		"PAG" : "Piper Light Aircraft",
		"PAH" : "Piper Navajo",
		"PAS" : "Piper Seneca",
		"PAT" : "Piper Turboprop",
		"PAZ" : "Piper Apache",
		"PL2" : "Pilatus PC12",
		"PL6" : "Pilatus PC6 Turbo Porter",
		"PN6" : "Partenavia P68 Victor",
		"PRI" : "Hawker 390",
		"RV1" : "IAI Arava",
		"S20" : "SAAB 2000",
		"S58" : "Sikorsky S58",
		"S61" : "Sikorsky S61",
		"S76" : "Sikorsky S76",
		"S80" : "MD80",
		"SA2" : "Saunders ST27",
		"SF3" : "SAAB SF340A/340B",
		"SFB" : "SAAB 340B",
		"SFF" : "SAAB 340 Freighter",
		"SH3" : "Shorts 330",
		"SH6" : "Shorts 360",
		"SHP" : "Shorts Skyliner",
		"SHS" : "Shorts Skyvan",
		"SU7" : "Superjet 100",
		"SU9" : "Superjet 100",
		"SWF" : "Fairchild SA226",
		"SWM" : "Fairchild Metroliner",
		"T20" : "Tupelov TU-204/214",
		"T2F" : "Tupelov TU-204 Freighter",
		"T34" : "Tupelov",
		"T5M" : "Tupelov TU-154 M",
		"TBM" : "SOCATA TBM-700",
		"TRD" : "Hawker Siddeley Trident",
		"TU3" : "Tupelov TU-134",
		"TU5" : "Tupelov TU-154",
		"VCV" : "Vickers Viscount",
		"VGF" : "Vickers Merchantman",
		"VGP" : "Vickers Vanguard",
		"WWP" : "IAI 1124 Westwind",
		"YK2" : "Yakovlev Yak-42",
		"YK4" : "Yakovlev Yak-40",
		"YN2" : "Harbin Y-12",
		"YN7" : "Xian Y-7",
		"YS1" : "NAMC YS-11"
	},
	"airlines" : {
		"2A" : "Deutsche Bahn",
		"2B" : "Ak Bars Aero",
		"2C" : "SNCF",
		"2D" : "Dynamic Airways",
		"2E" : "Smokey Bay Air",
		"2F" : "Afrinat International Airlines",
		"2G" : "Angara Airlines",
		"2H" : "Thalys International",
		"2I" : "Star Peru",
		"2J" : "Air Burkina",
		"2K" : "Aerolineas Galapagos",
		"2L" : "Helvetic Airways",
		"2N" : "Nextjet",
		"2P" : "PAL Express",
		"2T" : "Alajnihah Air Transport",
		"2Z" : "Passaredo Transportes",
		"3E" : "Multi-Aero",
		"3F" : "Pacific Airways",
		"3H" : "Air Inuit",
		"3J" : "Jubba Airways",
		"3K" : "Jetstar Asia",
		"3M" : "Silver Airways Corp",
		"3N" : "Air Urga",
		"3P" : "Tiara Air",
		"3Q" : "Carib Aviation Limited",
		"3R" : "Moskovia Airlines",
		"3S" : "Shuswap Air",
		"3T" : "Turan Air Airline Company",
		"3V" : "Waglisla Air",
		"3X" : "Japan Air Commuter",
		"4A" : "Thunderbird",
		"4C" : "LAN Colombia Airlines",
		"4D" : "Air Sinai",
		"4E" : "Tanana Air Service",
		"4F" : "Air City",
		"4K" : "Kenn Borek Air Ltd.",
		"4M" : "LAN Argentina",
		"4N" : "Air North",
		"4S" : "Star Airways",
		"4V" : "Lacbravo",
		"4W" : "Warbelow's Air Ventures",
		"4X" : "Atlantic Express",
		"4Y" : "Yute Air Alaska",
		"4Z" : "South African Airlink",
		"5B" : "Chanchangi Airlines",
		"5C" : "Nature Air",
		"5D" : "Aerolitoral",
		"5E" : "Siam GA",
		"5F" : "Pan African Airways",
		"5J" : "Cebu Pacific Air",
		"5K" : "Hi Fly",
		"5S" : "Servicios Aereos Profesionales",
		"5T" : "Canadian North",
		"5V" : "Everts",
		"5W" : "Speed Alliance Westbahn",
		"6A" : "Armenia Airways",
		"6C" : "Air Tomor",
		"6D" : "Travel Service",
		"6E" : "IndiGo Airlines",
		"6L" : "Aklak Air",
		"6P" : "Gryphon Airline",
		"6Q" : "Cham Wings Airlines",
		"6U" : "Air Cargo Germany",
		"7D" : "Donbassero Airlines",
		"7F" : "First Air",
		"7H" : "Era Aviation",
		"7N" : "Pan American World",
		"7P" : "Air Panama",
		"7Q" : "Elite Airways",
		"7R" : "Rusline",
		"7W" : "Wind Rose Aviation",
		"8A" : "Panama Airways",
		"8E" : "Bering Air",
		"8F" : "STP Airways",
		"8G" : "Girjet",
		"8H" : "Harbor Air Service",
		"8J" : "Linea Aerea EcoJet",
		"8N" : "Regional Air Services",
		"8P" : "Pacific Coastal Airlines",
		"8R" : "SOL Lineas Aereas",
		"8U" : "Afriqiyah Airways",
		"9A" : "Aladia Airlines",
		"9C" : "Spring Airlines",
		"9E" : "Endeavor Air",
		"9F" : "Eurostar",
		"9H" : "Dutch Antilles Express",
		"9K" : "Cape Air",
		"9M" : "Central Mountain Air",
		"9N" : "Tropic Air",
		"9P" : "Petra Airlines",
		"9R" : "SATENA",
		"9T" : "ACT Airlines",
		"9U" : "Air Moldova",
		"9V" : "Avior",
		"9W" : "Jet Airways",
		"A2" : "Astra Airlines",
		"A3" : "Aegean Airlines",
		"A4" : "Aerocomercial Oriente Norte",
		"A5" : "Hop",
		"AA" : "American Airlines",
		"AB" : "Air Berlin",
		"AC" : "Air Canada",
		"AD" : "Azul Brazilian Airlines",
		"AE" : "Mandarin Airlines",
		"AF" : "Air France",
		"AH" : "Air Algerie",
		"AI" : "Air India",
		"AJ" : "Aztec Worldwide Airlines",
		"AK" : "Airasia Sdn Bhd.",
		"AL" : "Alsair S.A.",
		"AM" : "Aeromexico",
		"AN" : "Ansett Australia",
		"AO" : "Australian Airlines",
		"AR" : "Aerolineas Argentinas",
		"AS" : "Alaska Airlines",
		"AT" : "Royal Air Maroc",
		"AU" : "Austral Lineas Aereas Sa",
		"AV" : "Avianca",
		"AX" : "Trans States Airlines",
		"AY" : "Finnair",
		"AZ" : "Alitalia",
		"B2" : "Belavia",
		"B3" : "Tashi Air",
		"B6" : "Jetblue Airways",
		"B7" : "Uni Airways",
		"BA" : "British Airways",
		"BC" : "Skymark Arilines",
		"BD" : "BMI",
		"BE" : "Flybe",
		"BF" : "Vincent Aviation",
		"BG" : "Biman Bangladesh Airlines",
		"BI" : "Royal Brunei",
		"BK" : "Okay Airways",
		"BL" : "Jetstar Pacific",
		"BN" : "Horizon Airlines",
		"BO" : "BB Airways",
		"BP" : "Air Botswana",
		"BQ" : "Bravo Airlines",
		"BR" : "Eva Air",
		"BU" : "Compagnie Africaine d'Aviation",
		"BW" : "Caribbean Airlines",
		"BX" : "Air Busan",
		"C6" : "Canjet Airlines",
		"C9" : "Cirrus Airlines",
		"CA" : "Air China",
		"CC" : "Macair Airlines",
		"CD" : "Alliance Air",
		"CE" : "Chalair Aviation",
		"CH" : "Bemidji Airlines",
		"CI" : "China Airlines",
		"CJ" : "BA Cityflyer",
		"CL" : "Lufthansa Cityline",
		"CM" : "Copa Airlines",
		"CO" : "Continental Airlines",
		"CP" : "Compass Airlines",
		"CQ" : "Czech Connect Airlines",
		"CS" : "Continental Micronesia",
		"CT" : "Alitalia City Liner",
		"CU" : "Cubana De Aviacion",
		"CW" : "Air Marshall Islands",
		"CX" : "Cathay Pacific",
		"CY" : "Cyprus Airways",
		"CZ" : "China Southern Airlines",
		"D6" : "Air Inter",
		"D7" : "Air Asia",
		"DA" : "Air Georgia",
		"DB" : "Hop Brit Air",
		"DC" : "Braathens Regional",
		"DE" : "Condor",
		"DF" : "Condor Berlin",
		"DH" : "Douniah Airlines",
		"DI" : "Cambodia Airlines",
		"DJ" : "Virgin Australia",
		"DK" : "Eastland Air",
		"DL" : "Delta Air Lines",
		"DM" : "Asian Air",
		"DN" : "Senegal Airlines",
		"DP" : "Perla Airlines",
		"DQ" : "Delta Connection",
		"DS" : "Easyjet Switzerland",
		"DT" : "TAAG Angola Airlines",
		"DV" : "Nantucket Airlines",
		"DW" : "Aero-Charter",
		"DX" : "Danish Air Transport",
		"E3" : "Sabaidee Airways",
		"E5" : "Air Arabia Egypt",
		"E6" : "Bringer Air Cargo",
		"E8" : "City Airways",
		"EC" : "Openskies",
		"ED" : "Air Explore",
		"EG" : "East Air",
		"EH" : "ANA Wings",
		"EI" : "Aer Lingus",
		"EK" : "Emirates",
		"EL" : "Ellinair",
		"EN" : "Air Dolomiti",
		"EP" : "Iran Asseman Airlines",
		"EQ" : "TAME EP",
		"ET" : "Ethiopian Airlines",
		"EU" : "Chengdu Airlines",
		"EV" : "Express Jet",
		"EW" : "Eurowings",
		"EY" : "Etihad Airways",
		"F4" : "International Flying Services",
		"FD" : "Thai AirAsia",
		"FG" : "Ariana Afghan Airlines",
		"FI" : "Icelandair",
		"FJ" : "Fiji Airways",
		"FK" : "Flamenco Airways",
		"FQ" : "Brindabella Airlines",
		"FR" : "Ryanair",
		"FT" : "Farnair Switzerland",
		"FZ" : "flydubai",
		"G3" : "VRG Linhas Aereas",
		"G4" : "Allegiant Air",
		"G6" : "Ghadames Air Transport",
		"G7" : "Gojet Airlines",
		"GA" : "Garuda Indonesia",
		"GC" : "Gambia Intl Airways",
		"GE" : "Transasia Airways",
		"GF" : "Gulf Air",
		"GH" : "Globus",
		"GL" : "Air Greenland",
		"GQ" : "Sky Express",
		"GR" : "Aurigny Air Services",
		"GT" : "Vista Georgia",
		"GU" : "Aviateca",
		"GW" : "SkyGreece Airlines",
		"GX" : "Primera Air",
		"GY" : "Sky Bishkek",
		"GZ" : "Air Rarotonga",
		"H5" : "Haiti Aviation",
		"H8" : "Hesa Airlines",
		"HA" : "Hawaiian Airlines",
		"HD" : "Air Do",
		"HF" : "Air Cote d'Ivoire",
		"HG" : "Niki",
		"HI" : "Papillon Airways",
		"HJ" : "Hellas Jet",
		"HM" : "Air Seychelles",
		"HP" : "Amapola Flyg",
		"HQ" : "Thomas Cook Airlines Belgium",
		"HR" : "Hahn Airlines",
		"HS" : "Svenska Direktflyg AB",
		"HV" : "Transavia Airlines",
		"HX" : "Hong Kong Airlines",
		"HY" : "Uzbekistan Airways",
		"HZ" : "Aurora Airlines",
		"IA" : "Iraqi Airways",
		"IB" : "Iberia",
		"IC" : "Indian Airlines",
		"ID" : "Batik Air Indonesia",
		"IE" : "Solomon Airlines",
		"IF" : "Islas Airways",
		"IG" : "Meridiana Fly",
		"IH" : "Irtysh-Air",
		"IK" : "Ikar Airlines",
		"IL" : "Trigana Air Service",
		"IN" : "Macedonian Airlines",
		"IQ" : "Augsburg Airways",
		"IR" : "Iran Air",
		"IV" : "Caspian Airlines",
		"IW" : "Wings Air",
		"IX" : "Air india Charter",
		"IY" : "Yemen Airways",
		"IZ" : "Arkia",
		"J2" : "Azerbaijan Airlines",
		"JB" : "Helijet International",
		"JD" : "Beijing Capital Airlines",
		"JF" : "Jet Asia Airways",
		"JH" : "Fuji Dream Airlines",
		"JJ" : "TAM Linhas Aereas",
		"JK" : "Spanair",
		"JL" : "Japan Airlines",
		"JM" : "Air Jamaica",
		"JO" : "JAL Ways",
		"JP" : "Adria Airways",
		"JQ" : "Jetstar",
		"JR" : "Aero California",
		"JS" : "Air Koryo",
		"JT" : "Lion Airlines",
		"JU" : "JAT Airways",
		"JV" : "Bearskin Airlines",
		"JX" : "Nice Helicopters",
		"K2" : "Eurolot",
		"K4" : "Kazakstan Airlines",
		"K9" : "Tonlesap Airlines",
		"KA" : "Dragonair",
		"KB" : "Druk Air",
		"KC" : "Air Astana",
		"KD" : "Kalstar Aviation",
		"KE" : "Korean Air",
		"KF" : "Blue1",
		"KJ" : "Air Incheion",
		"KK" : "Atlasjet Airlines",
		"KL" : "KLM Royal Dutch Airlines",
		"KM" : "Air Malta",
		"KQ" : "Kenya Airways",
		"KR" : "Air Bishkek",
		"KS" : "Penair",
		"KT" : "Kharkiv Airlines",
		"KU" : "Kuwait Airways",
		"KX" : "Cayman Airways",
		"KY" : "Kunming Airlines",
		"L4" : "Linea Turistica Aereotuy",
		"L6" : "Air Maldives",
		"L9" : "Air Mali S.A.",
		"LA" : "LAN Airlines",
		"LB" : "LEPL",
		"LF" : "Lao Central Airlines",
		"LG" : "Luxair",
		"LH" : "Lufthansa",
		"LI" : "Liat",
		"LJ" : "Sierra National Airlines",
		"LK" : "Kyrgyz Airlines",
		"LM" : "Loganair",
		"LN" : "Libyan Airlines",
		"LO" : "LOT Polish Airlines",
		"LP" : "LAN Peru",
		"LR" : "LACSA",
		"LS" : "Jet2.com",
		"LT" : "Air Lituanica",
		"LU" : "LAN Express",
		"LV" : "MEGA Maldives",
		"LW" : "Pacific Wings",
		"LX" : "Swiss International Airlines",
		"LY" : "El Al Israel Airlines",
		"LZ" : "Belle Air",
		"M4" : "Smart Aviation",
		"MA" : "Malev Hungarian Airlines",
		"MD" : "Air Madagascar",
		"ME" : "Middle East Airlines",
		"MF" : "Xiamen Airlines",
		"MH" : "Malaysia Airlines",
		"MI" : "Silkair",
		"MJ" : "Mihin Lanka",
		"MK" : "Air Mauritius",
		"MM" : "Peach Aviation",
		"MN" : "Comair Ltd",
		"MO" : "Calm Air International",
		"MP" : "Martinair",
		"MQ" : "Envoy Air",
		"MR" : "Hunnu Air",
		"MS" : "Egyptair",
		"MU" : "China Eastern Airways",
		"MW" : "Mokulele Airlines",
		"MX" : "Mexicana",
		"MZ" : "SAEREO",
		"N2" : "Dagestan Airlines",
		"N3" : "Omskavia",
		"N6" : "Aero Continente",
		"NA" : "North American Airlines",
		"NB" : "Sterling Airways",
		"NC" : "National Jet Systems",
		"NF" : "Air Vanuatu",
		"NG" : "Aero Contractors Company Nigeria",
		"NH" : "All Nippon Airways",
		"NI" : "Portugalia",
		"NL" : "Shaheen Air International",
		"NN" : "Air Martinique",
		"NO" : "Neos Spa",
		"NQ" : "Air Japan Company Ltd",
		"NR" : "Norontair",
		"NT" : "Binter Canarias",
		"NU" : "Japan Transocean Air",
		"NV" : "NWT Air",
		"NX" : "Air Macau",
		"NZ" : "Air New Zealand",
		"OA" : "Olympic Air",
		"OF" : "Air Finland",
		"OI" : "Hinterland Aviation",
		"OK" : "Czech Airlines",
		"OL" : "OLT Express Germany",
		"OM" : "MIAT Mongolian Airlines",
		"ON" : "Our Airline",
		"OO" : "Skywest Airlines",
		"OP" : "Chalk Ocean Airways",
		"OQ" : "Chongqing Airlines",
		"OR" : "Arkefly",
		"OS" : "Austrian Airlines",
		"OT" : "Aeropelican Air Services",
		"OU" : "Croatia Airlines",
		"OV" : "Estonian Air",
		"OW" : "Executive Airlines",
		"OX" : "Orient Thai Airlines",
		"OZ" : "Asiana Airlines",
		"P0" : "Proflight Commuter",
		"P2" : "Airkenya Express",
		"P9" : "Topair Ltd",
		"PC" : "Pegasus Airlines",
		"PD" : "Pemair",
		"PE" : "Phoebus Apolli Aviation",
		"PF" : "Primera Air",
		"PG" : "Bangkok Airways",
		"PH" : "Polynesian Airlines",
		"PI" : "Polar Airlines",
		"PJ" : "Air Saint Pierre",
		"PK" : "Pakistan International",
		"PM" : "Canary Fly",
		"PR" : "Philippine Airlines",
		"PS" : "Ukraine International Airlines",
		"PU" : "PLUNA",
		"PV" : "Saint Barth Commuter",
		"PX" : "Air Niugini",
		"PY" : "Surinam Airways Ltd.",
		"PZ" : "TAM Mercosur",
		"Q3" : "Anguilla Air Services",
		"Q5" : "Forty Mile Air",
		"QB" : "Qeshm Airlines",
		"QC" : "Camair-Co",
		"QF" : "Qantas Airways",
		"QG" : "Citilink Indonesia",
		"QH" : "Air Kyrgyzstan",
		"QI" : "Cimber A/S",
		"QJ" : "Latpass Airlines",
		"QK" : "Air Nova",
		"QL" : "LASER Airlines",
		"QM" : "Air Malawi",
		"QO" : "Quantum Air",
		"QQ" : "Alliance Airlines",
		"QR" : "Qatar Airways",
		"QS" : "Smartwings",
		"QU" : "Airline UTair Ukraine",
		"QV" : "Lao Airlines",
		"QX" : "Horizon Air",
		"QZ" : "PT Indonesia AirAsia",
		"R2" : "Orenair",
		"R4" : "Reliable Unique Services",
		"R7" : "Aserca Airlines",
		"R8" : "Kyrghyzstan Airlines",
		"RA" : "Nepal Airlines",
		"RB" : "Syrian Arab Airlines",
		"RC" : "Atlantic Airways",
		"RE" : "Aer Arann",
		"RG" : "Rotana Jet",
		"RI" : "Mandala Airlines",
		"RJ" : "Royal Jordanian",
		"RM" : "Rutaca",
		"RO" : "TAROM",
		"RP" : "Chautauqua Airlines",
		"RQ" : "Kam Air",
		"RR" : "Royal Air Force",
		"RS" : "Sky regional Airlines",
		"RT" : "Rak Airways",
		"RV" : "Air Canada Rouge",
		"RY" : "Royal Jordanian",
		"RZ" : "Sansa Airlines",
		"S4" : "Sata International",
		"S7" : "Siberia Airlines",
		"S9" : "Starbow",
		"SA" : "South African Airways",
		"SB" : "Aircalin",
		"SC" : "Shangdong Airlines",
		"SD" : "Sudan Airways",
		"SG" : "Spicejet",
		"SH" : "Sharp Aviation",
		"SI" : "Blue Islands",
		"SJ" : "PT Sriwijaya Air",
		"SK" : "Scandinavian Airlines",
		"SL" : "Thai Lion Mentari",
		"SN" : "Brussels Airlines",
		"SO" : "Salsa d Haiti",
		"SP" : "Sata Air Acores",
		"SQ" : "Singapore Airlines",
		"SU" : "Aeroflot",
		"SV" : "Saudi Arabian Airlines",
		"SW" : "Air Namibia",
		"SX" : "Skywork Airlines",
		"SY" : "Sun Country",
		"SZ" : "Aircompany Somon Air",
		"T2" : "Nakina Air Service",
		"T4" : "Trip",
		"T5" : "Turkmenistan Airlines",
		"T6" : "Onetime Airline",
		"TA" : "Taca International Airlines",
		"TB" : "JetAirFly",
		"TC" : "Air Tanzania",
		"TD" : "Atlantis European Airways",
		"TE" : "Lithuanian Airlines",
		"TG" : "Thai Airways International",
		"TI" : "Tailwind Airlines",
		"TK" : "Turkish Airlines",
		"TL" : "Airnorth",
		"TM" : "LAM Mocambique",
		"TN" : "Air Tahiti Nui",
		"TO" : "Alkan Air Ltd.",
		"TP" : "TAP Portugal",
		"TQ" : "Tandem Aero",
		"TR" : "Tiger Airways",
		"TS" : "Air Transat",
		"TT" : "Tiger Airways Australia",
		"TU" : "Tunis Air",
		"TV" : "Tibet Airlines",
		"TW" : "T'Way Air",
		"TY" : "Air Caledonie",
		"TZ" : "Scoot",
		"U6" : "Ural Airlines",
		"UA" : "United Airlines",
		"UC" : "LAN Chile Cargo",
		"UD" : "Hex Air",
		"UE" : "Nasair",
		"UG" : "Tunisair Express",
		"UL" : "SriLankan Airlines",
		"UM" : "Air Zimbabwe",
		"UO" : "Hang Kong Express Airways",
		"UP" : "Bahamasair",
		"UR" : "Utair Express",
		"US" : "US Airways",
		"UT" : "Utair Aviation",
		"UU" : "Air Austral",
		"UW" : "Universal Airlines",
		"UX" : "Air Europa",
		"UY" : "Cameroon Airlines",
		"V7" : "Air Senegal International",
		"VA" : "Virgin Australia Intl",
		"VB" : "Aeroenlaces Nacionales",
		"VD" : "Hennan Airlines",
		"VE" : "Aerovias Venezolanas",
		"VF" : "Valuair",
		"VG" : "VLM",
		"VI" : "Volga Dnepr Airline",
		"VK" : "Air Nigeria",
		"VM" : "Macair Jet",
		"VN" : "Vietnam Airlines",
		"VO" : "Tyrolean Airways",
		"VP" : "Villa Air",
		"VQ" : "Novoair",
		"VR" : "TACV Cabo Verde Airlines",
		"VS" : "Virgin Atlantic",
		"VT" : "Air Tahiti",
		"VU" : "Air Ivoire",
		"VV" : "Aerosvit Airlines",
		"VW" : "Aeromar",
		"VX" : "Virgin America",
		"W5" : "Mahan Airlines",
		"WA" : "KLM Cityhopper",
		"WB" : "Rwandair Express",
		"WC" : "Islena Airlines",
		"WD" : "Amsterdam Airlines",
		"WE" : "Thai Smile Airways",
		"WF" : "Wideroe",
		"WG" : "Sunwing Airlines",
		"WH" : "West African Airlines",
		"WJ" : "Labrador Airways Limited",
		"WM" : "Windward Islands Airways",
		"WN" : "Southwest Airlines",
		"WO" : "World Airways",
		"WP" : "Island Air",
		"WQ" : "Romavia",
		"WR" : "Aviaprad",
		"WS" : "WestJet",
		"WT" : "Wasaya Airways",
		"WV" : "Midwest Airlines",
		"WX" : "CityJet",
		"WY" : "Oman Air",
		"X5" : "Cronus Airlines",
		"XE" : "ExpressJet",
		"XF" : "Vladivostok Air",
		"XG" : "Sunexpress Germany",
		"XJ" : "Thai AirAsia X",
		"XO" : "Seair",
		"XQ" : "Action Airlines",
		"XR" : "Skywest Airlines",
		"XW" : "Walkers Cay Airline",
		"XZ" : "South African Express",
		"Y2" : "African Joint Air Services",
		"Y4" : "Eagle Aviation",
		"Y7" : "Taimyr",
		"YE" : "Yan Air",
		"YI" : "Air Sunshine Inc.",
		"YK" : "Aviva Traffic Company",
		"YL" : "Crystal Thai Arlines",
		"YM" : "Montenegro Airlines",
		"YN" : "Air Creebec",
		"YO" : "Heli Air Monaco",
		"YP" : "Perimeter Aviation",
		"YQ" : "Polet Airlines",
		"YR" : "Scenic Airlines",
		"YU" : "EuroAtlantic Airways",
		"YV" : "Mesa Airlines",
		"YW" : "Air Nostrum",
		"YX" : "Republic Airline",
		"Z6" : "Dniproavia",
		"ZA" : "Skywings Asia Airlines",
		"ZB" : "Monarch Airlines",
		"ZC" : "Korongo Airlines",
		"ZD" : "Ewa Air",
		"ZE" : "Eastar Jet",
		"ZF" : "Athens Airways",
		"ZG" : "Grozny Avia",
		"ZI" : "Aigle Azur",
		"ZJ" : "Zambezi Airlines",
		"ZK" : "Great Lakes Aviation",
		"ZL" : "Regional Express",
		"ZO" : "Central Air Transport Services",
		"ZP" : "Silk Way Airlines",
		"ZQ" : "Air Azul",
		"ZR" : "Punto Azul",
		"ZU" : "Air Bashkortostan",
		"ZV" : "Zagros Airlines",
		"ZW" : "Air Wisconsin",
		"ZY" : "Syk Airlines",
		"I2" : "Iberia Express",
		"VY" : "Veuling Airlines",
		"XL" : "LAN Ecuador",
		"LP" : "LAN Peru"
	},
	"code_share_flight_range" : [
		"1-2",
		"2-30",
		"31-59",
		"60-89"
	],
	"international_flight_range" : [
		"89-119",
		"120-159",
		"160-169",
		"170-179",
		"180-266",
		"465-768",
		"800-899"
	],
	"booking_status" : {
		"GK" : "Confirmed",
		"GL" : "Waitlisted",
		"HK" : "Confirmed",
		"HL" : "Waitlisted",
		"HX" : "Cancelled",
		"KK" : "Confirmed",
		"KL" : "Confirmed",
		"PK" : "Confirmed",
		"PL" : "Waitlisted",
		"RQ" : "Waitlisted",
		"RR" : "Confirmed",
		"SA" : "Space Available",
		"TK" : "Time change",
		"TL" : "Time change",
		"TN" : "Time change",
		"UC" : "Cancelled",
		"UN" : "Cancelled"
	},
	"cabin_classes" : {
		"C" : "Business",
		"D" : "Business",
		"I" : "Business",
		"J" : "Business",
		"U" : "Business",
		"B" : "Economy",
		"E" : "Economy",
		"G" : "Economy",
		"H" : "Economy",
		"K" : "Economy",
		"L" : "Economy",
		"M" : "Economy",
		"N" : "Economy",
		"O" : "Economy",
		"Q" : "Economy",
		"S" : "Economy",
		"V" : "Economy",
		"X" : "Economy",
		"Y" : "Economy",
		"A" : "First",
		"F" : "First",
		"P" : "First",
		"R" : "Premium Economy",
		"T" : "Premium Economy",
		"W" : "Premium Economy",
		"Z" : "Premium Economy"
	},
	"meal_types" : {
		"AVML" : "Indian style vegetarian meal",
		"BBML" : "infant meal (0-11 months)",
		"CHML" : "child meal (2-11 years)",
		"DBML" : "diabetic meal",
		"FPML" : "fruit platter",
		"GFML" : "gluten intolerant meal",
		"HNML" : "Hindu meal",
		"KSML" : "Kosher meal",
		"MOML" : "Halal meal",
		"VGML" : "vegan vegetarian meal",
		"VJML" : "strict Indian vegetarian meal",
		"VLML" : "lacto-ovo vegetarian meal",
		"VOML" : "oriental vegetarian meal"
	},
	"seat_type" : {
		"W" : "Window",
		"A" : "Aisle",
		"E" : "Exit Row",
		"L" : "Extra Leg Room"
	},
	"titles" : {
		"Mr" : "Mister",
		"Mrs" : "Mrs",
		"Miss" : "Miss",
		"Ms" : "Ms",
		"Mstr" : "Master",
		"Master" : "Master",
		"Amb" : "Ambassador",
		"Brig" : "Brigadier",
		"Capt" : "Captain",
		"Dame" : "Dame",
		"Dr" : "Doctor",
		"Hon" : "Honourable",
		"Lady" : "Lady",
		"Lord" : "Lord",
		"Prof" : "Professor",
		"Rev" : "Reverend",
		"Sen" : "Senator",
		"Sir" : "Sir",
		"Ab" : "Able Seaman",
		"Ac" : "Aircraftman",
		"ACM" : "Air Chief Marshal",
		"AcR" : "Aircraftsman Recruit",
		"Acw" : "Aircraftwoman",
		"Adml" : "Admiral",
		"Adv" : "Advocate",
		"AirCdre" : "Air Commodore",
		"AirC" : "Air Commodore",
		"AirM" : "Air Marshal",
		"Alderman" : "Alderman",
		"Ald" : "Alderman",
		"App" : "Apprentice",
		"ArchBp" : "Arch Bishop",
		"ArcB" : "Arch Bishop",
		"ASlt" : "Acting Sub Lieutenant",
		"ArchDeacon" : "Arch Deacon",
		"ArcD" : "Arch Deacon",
		"AVM" : "Air Vice Marshal",
		"Baron" : "Baron",
		"Barn" : "Baron",
		"Baroness" : "Baroness",
		"Bars" : "Baroness",
		"Bp" : "Bishop",
		"Bdr" : "Bombardier",
		"Bro" : "Brother",
		"Cdt" : "Cadet",
		"Canon" : "Canon",
		"Cano" : "Canon",
		"Cardinal" : "Cardinal",
		"Card" : "Cardinal",
		"Cdre" : "Commodore",
		"Cfn" : "Craftsman",
		"Chap" : "Chaplain",
		"ChComm" : "Chief Commissioner",
		"ChCo" : "Chief Commissioner",
		"ChInsp" : "Chief Inspector",
		"ChIn" : "Chief Inspector",
		"Cmdr" : "Commander",
		"Col" : "Colonel",
		"Commandant" : "Commandant",
		"Comd" : "Commandant",
		"Comm" : "Commissioner",
		"ConGen" : "Consul General",
		"ConG" : "Consul General",
		"Const" : "Constable",
		"Cons" : "Constable",
		"Councillor" : "Councillor",
		"Coun" : "Councillor",
		"Countess" : "Countess",
		"Cous" : "Countess",
		"Count" : "Count",
		"Cout" : "Count",
		"Cpl" : "Corporal",
		"CPO" : "Chief Petty Officer",
		"Datin" : "Datin",
		"Dati" : "Datin",
		"Dato" : "Dato",
		"Det" : "Detective",
		"DetSgt" : "Detective Sergeant",
		"DetS" : "Detective Sergeant",
		"Duchess" : "Duchess",
		"Duch" : "Duchess",
		"Duke" : "Duke",
		"Fthr" : "Father",
		"Father" : "Father",
		"Fr" : "Father",
		"FltLt" : "Flight Lieutenant",
		"FlLt" : "Flight Lieutenant",
		"FSgt" : "Flight Sergeant",
		"FlgOff" : "Flying Officer",
		"FOff" : "Flying Officer",
		"Frau" : "Frau",
		"GpCapt" : "Group Captain",
		"GCapt" : "Group Captain",
		"Gen" : "General",
		"Gnr" : "Gunner",
		"Gov" : "Governor",
		"Guru" : "Guru",
		"HisExcellency" : "His Excellency",
		"HE" : "His Excellency",
		"Herr" : "Herr",
		"HonJustice" : "Honourable Justice",
		"HonJ" : "Honourable Justice",
		"HonMr" : "Honourable Minister",
		"HRH" : "HRH",
		"HerRoyalHighness" : "Her Royal Highness",
		"HisRoyalHighness" : "His Royal Highness",
		"Insp" : "Inspector",
		"Judge" : "Judge",
		"Judg" : "Judge",
		"Jnr" : "Junior",
		"Justice" : "Justice",
		"Just" : "Justice",
		"LAc" : "Leading Aircraftman",
		"LAcw" : "Leading Aircraftwoman",
		"LS" : "Leading Seaman",
		"LCpl" : "Lance Corporal",
		"LCdr" : "Lieutenant Commander",
		"LtCol" : "Lieutenant Colonel",
		"LCol" : "Lieutenant Colonel",
		"Lt" : "Lieutenant",
		"Leut" : "Lieutenant",
		"LtGen" : "Lieutenant General",
		"LGen" : "Lieutenant General",
		"Madam" : "Madam",
		"Mdm" : "Madam",
		"Madm" : "Madam",
		"Maj" : "Major",
		"MajGen" : "Major General",
		"MajG" : "Major General",
		"Marshal" : "Marshal",
		"Mars" : "Marshal",
		"Mayor" : "Mayor",
		"Mayo" : "Mayor",
		"Mdn" : "Midshipman",
		"Minister" : "Minister",
		"Minr" : "Minister",
		"Monk" : "Monk",
		"Msgr" : "Monsignor",
		"MP" : "Member of Parliament",
		"Mst" : "Master",
		"OCdt" : "Officer Cadet",
		"Officer" : "Officer",
		"Offi" : "Officer",
		"Pastor" : "Pastor",
		"Past" : "Pastor",
		"PltOff" : "Pilot Officer",
		"PlOF" : "Pilot Officer",
		"PO" : "Petty Officer",
		"Prince" : "Prince",
		"Prin" : "Prince",
		"Princess" : "Princess",
		"Prcs" : "Princess",
		"Pte" : "Private",
		"Rabbi" : "Rabbi",
		"RAdm" : "Rear Admiral",
		"Rct" : "Recruit",
		"Rec" : "Rector",
		"RevMthr" : "Reverend Mother",
		"RevM" : "Reverend Mother",
		"RevDr" : "Reverend Doctor",
		"RevD" : "Reverend Doctor",
		"RevSir" : "Reverend Sir",
		"RevS" : "Reverend Sir",
		"RSM" : "Regimental Sergeant Major",
		"RtHon" : "Right Honourable",
		"RtHo" : "Right Honourable",
		"Spr" : "Sapper",
		"Sap" : "Sapper",
		"SbLt" : "Sub Lieutenant",
		"SenConst" : "Senior Constable",
		"SenC" : "Senior Constable",
		"SenDet" : "Senior Detective",
		"SenD" : "Senior Detective",
		"Sgt" : "Sergeant",
		"Sig" : "Signalman",
		"Sister" : "Sister",
		"Sist" : "Sister",
		"SqnLdr" : "Squadron Leader",
		"SLdr" : "Squadron Leader",
		"Smn" : "Seaman",
		"Sr" : "Sen-your",
		"Sra" : "Sen-youra",
		"SSgt" : "Staff Sergeant",
		"Supt" : "Superintendent",
		"Swami" : "Swami",
		"Swam" : "Swami",
		"SWr" : "Senior Wran",
		"Tpr" : "Trooper",
		"TurLdr" : "Tour Leader",
		"VAdm" : "Vice Admiral",
		"VP" : "Vice President",
		"Venr" : "Venerable",
		"Vic" : "Vicar",
		"Viscount" : "Viscount",
		"Visc" : "Viscount",
		"Viscountess" : "Viscountess",
		"Viss" : "Viscountess",
		"WOff" : "Warrant Officer",
		"WO" : "Warrant Officer",
		"WOI" : "Warrant Officer Class 1",
		"WOII" : "Warrant Officer Class 2",
		"WgCdr" : "Wing Commander",
		"WCdr" : "Wing Commander"
	},
	"voucher_booking_codes" : [
		"QZW",
		"QZY",
		"QXM",
		"QXL",
		"GIF",
		"QPY"
	]
}